#!/usr/bin/env bash
# A Bash script that stops the 4-to_infinity_and_beyond process without using kill or killall

pid=$(pgrep -f 7-highlander)
[ -n "$pid" ] && echo "Terminating PID: $pid" && bash -c "exec -a terminator sh -c 'kill -15 $pid'"
